#pragma once

#include <stddef.h>
#include <lcom/lcf.h>

static xpm_row_t const ComboioCP[] = {
"100 200 2",
/* colors */
"  54",
"! 4",
/* pixels */
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                    !!!!!!!!!!!!!!!!!!!!                !!!!!!!!!!!!!!!!                    !!  ",
"  !!               !!!!!!!!!!!!!!!!!!!!!!!!!            !!!!!!!!!!!!!!!!!!!!!!!!!               !!  ",
"  !!            !!!!!!!!!!!!!!!!!!!!!!!!!!!            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!            !!  ",
"  !!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!  ",
"  !!         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         !!  ",
"  !!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!  ",
"  !!       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       !!  ",
"  !!      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      !!  ",
"  !!     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     !!  ",
"  !!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!  ",
"  !!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!  ",
"  !!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   !!  ",
"  !!   !!!!!!!!!!!!!!!!!                        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   !!  ",
"  !!   !!!!!!!!!!!!!!                          !!!!!!!!!!!!!                   !!!!!!!!!!!!!!   !!  ",
"  !!  !!!!!!!!!!!!!!                          !!!!!!!!!!!!!                     !!!!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!!                           !!!!!!!!!!!!                       !!!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                           !!!!!!!!!!!!                         !!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                           !!!!!!!!!!!!                         !!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                          !!!!!!!!!!!!                          !!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                          !!!!!!!!!!!!                           !!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                         !!!!!!!!!!!!                            !!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                        !!!!!!!!!!!!                            !!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!                        !!!!!!!!!!!!                            !!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!!                      !!!!!!!!!!!!                            !!!!!!!!!!!!!  !!  ",
"  !!  !!!!!!!!!!!!!                      !!!!!!!!!!!!                            !!!!!!!!!!!!!  !!  ",
"  !!   !!!!!!!!!!!!!                    !!!!!!!!!!!!                            !!!!!!!!!!!!!!  !!  ",
"  !!   !!!!!!!!!!!!!!!                !!!!!!!!!!!!!!                          !!!!!!!!!!!!!!!   !!  ",
"  !!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   !!  ",
"  !!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!  ",
"  !!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!  ",
"  !!     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     !!  ",
"  !!      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      !!  ",
"  !!      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      !!  ",
"  !!       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       !!  ",
"  !!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!  ",
"  !!          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          !!  ",
"  !!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           !!  ",
"  !!             !!!!!!!!!!!!!!!!!!!!!!!!!!!         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             !!  ",
"  !!                !!!!!!!!!!!!!!!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!                !!  ",
"  !!                                                !!!!!!!!!!!!!!!                             !!  ",
"  !!                                               !!!!!!!!!!!!!!                               !!  ",
"  !!                                               !!!!!!!!!!!!!!                               !!  ",
"  !!                                              !!!!!!!!!!!!!!                                !!  ",
"  !!                                             !!!!!!!!!!!!!!                                 !!  ",
"  !!                                             !!!!!!!!!!!!!!                                 !!  ",
"  !!                                            !!!!!!!!!!!!!!                                  !!  ",
"  !!                                            !!!!!!!!!!!!!!                                  !!  ",
"  !!                                           !!!!!!!!!!!!!!                                   !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  ",
"  !!                                                                                            !!  "
};


static xpm_row_t const sun[] = {
/* width height num_colors chars_per_pixel */
"50 50 2",
"  0",
"! 6",
"                                                  ",
"                       !                          ",
"                       !                          ",
"                       !                          ",
"                       !                    !     ",
"                       !                   !!     ",
"                       !                  !!      ",
"      !!               !                 !!       ",
"       !!                               !!        ",
"        !!                             !!         ",
"         !!                            !          ",
"          !!       !!!!!!!!!!!        !!          ",
"           !!    !!!!!!!!!!!!!!!      !           ",
"                !!!!!!!!!!!!!!!!!                 ",
"               !!!!!!!!!!!!!!!!!!!                ",
"              !!!!!!!!!!!!!!!!!!!!!               ",
"             !!!!!!!!!!!!!!!!!!!!!!!              ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"   !!!!!!  !!!!!!!!!!!!!!!!!!!!!!!!!!!  !!!!!!    ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"             !!!!!!!!!!!!!!!!!!!!!!!              ",
"              !!!!!!!!!!!!!!!!!!!!!               ",
"               !!!!!!!!!!!!!!!!!!!                ",
"                !!!!!!!!!!!!!!!!!                 ",
"           !!    !!!!!!!!!!!!!!!     !            ",
"          !!       !!!!!!!!!!!       !!           ",
"         !!                           !!          ",
"        !!                             !!         ",
"       !!                !              !         ",
"      !!                 !               !        ",
"      !                  !               !!       ",
"                         !                !       ",
"                         !                        ",
"                         !                        ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "
};

static xpm_row_t const moon[] = {
/* width height num_colors chars_per_pixel */
"50 50 2",
/* colors */
"  0",
"! 7",
/* pixels */
"                                                  ",
"                                                  ",
"                        !!!!!!!!!                 ",
"                       !!!!!!!!!!!!!!             ",
"                        !!!!!!!!!!!!!!!           ",
"                           !!!!!!!!!!!!!!         ",
"                             !!!!!!!!!!!!!        ",
"                               !!!!!!!!!!!!       ",
"                                !!!!!!!!!!!       ",
"                                !!!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!!     ",
"                                !!!!!!!!!!!!!     ",
"                                !!!!!!!!!!!!!     ",
"                               !!!!!!!!!!!!!!     ",
"                               !!!!!!!!!!!!!!     ",
"                              !!!!!!!!!!!!!!!     ",
"                             !!!!!!!!!!!!!!!!     ",
"                             !!!!!!!!!!!!!!!      ",
"                            !!!!!!!!!!!!!!!!      ",
"                            !!!!!!!!!!!!!!!!      ",
"                           !!!!!!!!!!!!!!!!!      ",
"                          !!!!!!!!!!!!!!!!!!      ",
"                          !!!!!!!!!!!!!!!!!!      ",
"                         !!!!!!!!!!!!!!!!!!!      ",
"                        !!!!!!!!!!!!!!!!!!!       ",
"                      !!!!!!!!!!!!!!!!!!!!!       ",
"                     !!!!!!!!!!!!!!!!!!!!!!       ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!!       ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!        ",
"  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!               ",
"           !!!!!!!!!!!!!!!!!!!!!                  ",
"               !!!!!!!!!!!!!                      ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "
};

static xpm_row_t const train[] = {
    "100 100 4",
"  0",
"O 36",
"H 7",
"X 20",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};


static xpm_row_t const tempNum0[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                     !!!!!!!!!!!!!!!!!                          ",
"                    !!!!!!!!!!!!!!!!!!!!                        ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!                      ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"               !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"             !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!               ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!              ",
"          !!!!!!!!!!!!!!!         !!!!!!!!!!!!!!!!!             ",
"         !!!!!!!!!!!!!!!            !!!!!!!!!!!!!!!             ",
"         !!!!!!!!!!!!!                !!!!!!!!!!!!!!            ",
"        !!!!!!!!!!!!!                  !!!!!!!!!!!!!            ",
"        !!!!!!!!!!!!                     !!!!!!!!!!!            ",
"       !!!!!!!!!!!!                       !!!!!!!!!!!           ",
"       !!!!!!!!!!!                         !!!!!!!!!!           ",
"      !!!!!!!!!!!                          !!!!!!!!!!           ",
"      !!!!!!!!!!!                          !!!!!!!!!!           ",
"      !!!!!!!!!!                            !!!!!!!!!!          ",
"     !!!!!!!!!!!                            !!!!!!!!!!          ",
"     !!!!!!!!!!                             !!!!!!!!!!          ",
"    !!!!!!!!!!!                             !!!!!!!!!!          ",
"    !!!!!!!!!!!                              !!!!!!!!!          ",
"    !!!!!!!!!!!                              !!!!!!!!!          ",
"    !!!!!!!!!!                               !!!!!!!!!          ",
"    !!!!!!!!!                                !!!!!!!!!          ",
"   !!!!!!!!!!                                !!!!!!!!!          ",
"   !!!!!!!!!!                                !!!!!!!!!          ",
"   !!!!!!!!!!                                !!!!!!!!!          ",
"   !!!!!!!!!!                               !!!!!!!!!!          ",
"   !!!!!!!!!                                !!!!!!!!!!          ",
"   !!!!!!!!!                                !!!!!!!!!!          ",
"   !!!!!!!!!                               !!!!!!!!!!!          ",
"   !!!!!!!!!                               !!!!!!!!!!           ",
"   !!!!!!!!!                               !!!!!!!!!!           ",
"   !!!!!!!!!                              !!!!!!!!!!!           ",
"   !!!!!!!!!!                            !!!!!!!!!!!            ",
"   !!!!!!!!!!                           !!!!!!!!!!!!            ",
"   !!!!!!!!!!                           !!!!!!!!!!!!            ",
"   !!!!!!!!!!!                         !!!!!!!!!!!!             ",
"    !!!!!!!!!!!                       !!!!!!!!!!!!!             ",
"    !!!!!!!!!!!!                     !!!!!!!!!!!!!              ",
"    !!!!!!!!!!!!!                 !!!!!!!!!!!!!!!               ",
"     !!!!!!!!!!!!!!!            !!!!!!!!!!!!!!!!                ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"             !!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"                !!!!!!!!!!!!!!!!!!!!                            ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};


/* XPM */
static xpm_row_t const tempNum1[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                    !!!!!!                      ",
"                                  !!!!!!!!!                     ",
"                                !!!!!!!!!!!!                    ",
"                              !!!!!!!!!!!!!!                    ",
"                            !!!!!!!!!!!!!!!!                    ",
"                           !!!!!!!!!!!!!!!!!                    ",
"                         !!!!!!!!!!!!!!!!!!!                    ",
"                        !!!!!!!!!!!!!!!!!!!!                    ",
"                       !!!!!!!!!!!!!!!!!!!!!!                   ",
"                     !!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                    !!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                   !!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                 !!!!!!!!!!!!!!!!!  !!!!!!!!!                   ",
"                !!!!!!!!!!!!!!!!    !!!!!!!!!                   ",
"               !!!!!!!!!!!!!!!!     !!!!!!!!!                   ",
"               !!!!!!!!!!!!!!!      !!!!!!!!!                   ",
"              !!!!!!!!!!!!!!        !!!!!!!!!                   ",
"              !!!!!!!!!!!!!         !!!!!!!!!                   ",
"              !!!!!!!!!!!           !!!!!!!!!                   ",
"              !!!!!!!!!!            !!!!!!!!!                   ",
"              !!!!!!!!!             !!!!!!!!!                   ",
"              !!!!!!!!!             !!!!!!!!!                   ",
"               !!!!!!!              !!!!!!!!!                   ",
"                !!!!!               !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!                   ",
"                                    !!!!!!!!!!                  ",
"                                    !!!!!!!!!!                  ",
"                                    !!!!!!!!!!                  ",
"                                    !!!!!!!!!!                  ",
"                                     !!!!!!!!!                  ",
"                                      !!!!!!!                   ",
"                                       !!!!!                    ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum2[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"            !!!!!!!!!!!!!!!!!!!!                                ",
"           !!!!!!!!!!!!!!!!!!!!!!!                              ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!                             ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"        !!!!!!!!!!          !!!!!!!!!!!                         ",
"        !!!!!!!!!            !!!!!!!!!!                         ",
"         !!!!!!!             !!!!!!!!!!                         ",
"          !!!!!               !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                             !!!!!!!!!!                         ",
"             !!!!!!!!!!!     !!!!!!!!!!                         ",
"            !!!!!!!!!!!!!!!  !!!!!!!!!!                         ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
"     !!!!!!!!!!!!   !!!!!!!!!!!!!!!!!!                          ",
"     !!!!!!!!!!!      !!!!!!!!!!!!!!!!                          ",
"     !!!!!!!!!!          !!!!!!!!!!!!!!                         ",
"     !!!!!!!!!!!          !!!!!!!!!!!!!!!      !!!!!            ",
"     !!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
"      !!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
"          !!!!!!!!!!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!       !!!!!!!!!!!!!!             ",
"             !!!!!!!!!!!!!!!!                                   ",
"                !!!!!!!!!!!!                                    ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum3[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"             !!!!!!!!!!!!!!!!!                                  ",
"            !!!!!!!!!!!!!!!!!!!!!!!!                            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!               ",
"             !!!!!        !!!!!!!!!!!!!!!!!!!!!!!               ",
"                                !!!!!!!!!!!!!!!!!!              ",
"                                    !!!!!!!!!!!!!!!             ",
"                                       !!!!!!!!!!!!             ",
"                                        !!!!!!!!!!!             ",
"                                         !!!!!!!!!!             ",
"                                         !!!!!!!!!!             ",
"                                        !!!!!!!!!!!             ",
"                                       !!!!!!!!!!!!             ",
"                                     !!!!!!!!!!!!!              ",
"                                 !!!!!!!!!!!!!!!!!              ",
"                             !!!!!!!!!!!!!!!!!!!!               ",
"                            !!!!!!!!!!!!!!!!!!!!!               ",
"                           !!!!!!!!!!!!!!!!!!!!!                ",
"                           !!!!!!!!!!!!!!!!!!!!                 ",
"                           !!!!!!!!!!!!!!!!!!!                  ",
"                           !!!!!!!!!!!!!!!!!!!                  ",
"                           !!!!!!!!!!!!!!!!!!!!                 ",
"                            !!!!!!!!!!!!!!!!!!!                 ",
"                             !!!!!!!!!!!!!!!!!!!                ",
"                                !!!!!!!!!!!!!!!!                ",
"                                     !!!!!!!!!!!!               ",
"                                      !!!!!!!!!!!               ",
"                                       !!!!!!!!!!!              ",
"                                       !!!!!!!!!!!              ",
"                                        !!!!!!!!!!              ",
"                                        !!!!!!!!!!              ",
"                                        !!!!!!!!!!              ",
"                                       !!!!!!!!!!!              ",
"                                      !!!!!!!!!!!!              ",
"                                     !!!!!!!!!!!!               ",
"                                   !!!!!!!!!!!!!!               ",
"                                !!!!!!!!!!!!!!!!!               ",
"                              !!!!!!!!!!!!!!!!!!                ",
"        !!!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!!!!!!                 ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!                              ",
"                   !!!!!!!!!!!                                  ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum4[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"               !!!!!                                            ",
"              !!!!!!!                                           ",
"             !!!!!!!!!                                          ",
"             !!!!!!!!!                                          ",
"             !!!!!!!!!                                          ",
"            !!!!!!!!!!                                          ",
"            !!!!!!!!!!                                          ",
"            !!!!!!!!!!           !!!!!                          ",
"           !!!!!!!!!!!          !!!!!!!                         ",
"           !!!!!!!!!!          !!!!!!!!!                        ",
"          !!!!!!!!!!!         !!!!!!!!!!                        ",
"          !!!!!!!!!!!         !!!!!!!!!!                        ",
"          !!!!!!!!!!          !!!!!!!!!!                        ",
"         !!!!!!!!!!!          !!!!!!!!!!                        ",
"         !!!!!!!!!!           !!!!!!!!!                         ",
"         !!!!!!!!!!          !!!!!!!!!!                         ",
"        !!!!!!!!!!!          !!!!!!!!!!                         ",
"        !!!!!!!!!!           !!!!!!!!!!                         ",
"        !!!!!!!!!!           !!!!!!!!!!                         ",
"       !!!!!!!!!!!           !!!!!!!!!                          ",
"       !!!!!!!!!!           !!!!!!!!!!                          ",
"      !!!!!!!!!!!           !!!!!!!!!!                          ",
"      !!!!!!!!!!!           !!!!!!!!!!                          ",
"      !!!!!!!!!!            !!!!!!!!!!                          ",
"     !!!!!!!!!!!           !!!!!!!!!!                           ",
"     !!!!!!!!!!!           !!!!!!!!!!                           ",
"     !!!!!!!!!!!!!!!!      !!!!!!!!!!                           ",
"     !!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!                           ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"                      !!!!!!!!!!!!!!!!!!!!!!!!!!                ",
"                          !!!!!!!!!!!!!!!!!!!!!                 ",
"                         !!!!!!!!!!!!!!!!!!!!!                  ",
"                         !!!!!!!!!!                             ",
"                         !!!!!!!!!!                             ",
"                         !!!!!!!!!!                             ",
"                         !!!!!!!!!                              ",
"                         !!!!!!!!!                              ",
"                         !!!!!!!!!                              ",
"                         !!!!!!!!!                              ",
"                        !!!!!!!!!!                              ",
"                        !!!!!!!!!!                              ",
"                        !!!!!!!!!!                              ",
"                        !!!!!!!!!!                              ",
"                        !!!!!!!!!                               ",
"                         !!!!!!!                                ",
"                          !!!!!                                 ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum5[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"          !!!!!!!!!!                                            ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!                                             ",
"          !!!!!!!!!!!!!!!!!!                                    ",
"          !!!!!!!!!!!!!!!!!!!!!!!                               ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"             !!!!!!     !!!!!!!!!!!!!!!!!!!                     ",
"                             !!!!!!!!!!!!!!                     ",
"                               !!!!!!!!!!!!                     ",
"                                 !!!!!!!!!!                     ",
"                                  !!!!!!!!!                     ",
"                                  !!!!!!!!!                     ",
"                                  !!!!!!!!!                     ",
"                                  !!!!!!!!!                     ",
"                                  !!!!!!!!!                     ",
"                                 !!!!!!!!!!                     ",
"                                 !!!!!!!!!!                     ",
"                                 !!!!!!!!!!                     ",
"                                !!!!!!!!!!!                     ",
"                              !!!!!!!!!!!!                      ",
"                          !!!!!!!!!!!!!!!!                      ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"             !!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"             !!!!!!!!!!!!!!!!!!!!!                              ",
"              !!!!!!!!!!!!!!!!                                  ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum6[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                    !!!!!                       ",
"                                  !!!!!!!!                      ",
"                               !!!!!!!!!!!!                     ",
"                             !!!!!!!!!!!!!!                     ",
"                            !!!!!!!!!!!!!!!                     ",
"                          !!!!!!!!!!!!!!!!!                     ",
"                         !!!!!!!!!!!!!!!!!!                     ",
"                        !!!!!!!!!!!!!!!!!!                      ",
"                       !!!!!!!!!!!!!!!!!!                       ",
"                      !!!!!!!!!!!!!!!!!!                        ",
"                     !!!!!!!!!!!!!!!!!                          ",
"                     !!!!!!!!!!!!!!                             ",
"                    !!!!!!!!!!!!!                               ",
"                   !!!!!!!!!!!!!                                ",
"                  !!!!!!!!!!!!!                                 ",
"                  !!!!!!!!!!!!                                  ",
"                 !!!!!!!!!!!!                                   ",
"                !!!!!!!!!!!!!                                   ",
"               !!!!!!!!!!!!!                                    ",
"               !!!!!!!!!!!!                                     ",
"               !!!!!!!!!!!                                      ",
"              !!!!!!!!!!!!                                      ",
"              !!!!!!!!!!!!!!!!!                                 ",
"              !!!!!!!!!!!!!!!!!!!!!!!!                          ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"              !!!!!!!!!    !!!!!!!!!!!!!!!!!!!!                 ",
"              !!!!!!!!!           !!!!!!!!!!!!!                 ",
"              !!!!!!!!!             !!!!!!!!!!!                 ",
"              !!!!!!!!!!             !!!!!!!!!!                 ",
"              !!!!!!!!!!             !!!!!!!!!!                 ",
"              !!!!!!!!!!!             !!!!!!!!!                 ",
"              !!!!!!!!!!!!            !!!!!!!!!                 ",
"               !!!!!!!!!!!            !!!!!!!!!                 ",
"               !!!!!!!!!!!!         !!!!!!!!!!!                 ",
"                !!!!!!!!!!!!!     !!!!!!!!!!!!!                 ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                   !!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"                    !!!!!!!!!!!!!!!!!!!!!!!                     ",
"                      !!!!!!!!!!!!!!!!!!!!                      ",
"                       !!!!!!!!!!!!!!!!!                        ",
"                         !!!!!!!!!!!!!!                         ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum7[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!              ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"                                        !!!!!!!!!!!             ",
"                                       !!!!!!!!!!!!             ",
"                                      !!!!!!!!!!!!              ",
"                                      !!!!!!!!!!!               ",
"                                     !!!!!!!!!!!!               ",
"                                    !!!!!!!!!!!!                ",
"                                    !!!!!!!!!!!                 ",
"                                   !!!!!!!!!!!!                 ",
"                                   !!!!!!!!!!!                  ",
"                                  !!!!!!!!!!!                   ",
"                                  !!!!!!!!!!!                   ",
"                                 !!!!!!!!!!!                    ",
"                                 !!!!!!!!!!!                    ",
"                                !!!!!!!!!!!                     ",
"                                !!!!!!!!!!!                     ",
"                               !!!!!!!!!!!                      ",
"                              !!!!!!!!!!!!                      ",
"                             !!!!!!!!!!!!                       ",
"                             !!!!!!!!!!!!                       ",
"                            !!!!!!!!!!!!                        ",
"                            !!!!!!!!!!!!                        ",
"                           !!!!!!!!!!!!                         ",
"                           !!!!!!!!!!!                          ",
"                          !!!!!!!!!!!                           ",
"                          !!!!!!!!!!!                           ",
"                         !!!!!!!!!!!                            ",
"                        !!!!!!!!!!!!                            ",
"                        !!!!!!!!!!!                             ",
"                       !!!!!!!!!!!!                             ",
"                       !!!!!!!!!!!                              ",
"                       !!!!!!!!!!!                              ",
"                      !!!!!!!!!!!                               ",
"                      !!!!!!!!!!!                               ",
"                     !!!!!!!!!!!                                ",
"                     !!!!!!!!!!!                                ",
"                     !!!!!!!!!!                                 ",
"                     !!!!!!!!!!                                 ",
"                     !!!!!!!!!                                  ",
"                      !!!!!!!                                   ",
"                       !!!!!                                    ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum8[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                       !!!!!!!!!!!                              ",
"                      !!!!!!!!!!!!!!                            ",
"                     !!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!!!!                         ",
"                   !!!!!!!!!!!!!!!!!!!!!                        ",
"                  !!!!!!!!!!!!!!!!!!!!!!!                       ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!                      ",
"                !!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"                !!!!!!!!!!!!!!!!!!!!!!!!!!!                     ",
"               !!!!!!!!!!!!!  !!!!!!!!!!!!!                     ",
"              !!!!!!!!!!!!!     !!!!!!!!!!!                     ",
"             !!!!!!!!!!!!!       !!!!!!!!!!                     ",
"             !!!!!!!!!!!!         !!!!!!!!!                     ",
"            !!!!!!!!!!!!          !!!!!!!!!                     ",
"            !!!!!!!!!!!          !!!!!!!!!!                     ",
"            !!!!!!!!!!           !!!!!!!!!!                     ",
"            !!!!!!!!!!           !!!!!!!!!!                     ",
"            !!!!!!!!!           !!!!!!!!!!!                     ",
"            !!!!!!!!!           !!!!!!!!!!!                     ",
"            !!!!!!!!!!         !!!!!!!!!!!                      ",
"            !!!!!!!!!!!       !!!!!!!!!!!!                      ",
"            !!!!!!!!!!!     !!!!!!!!!!!!!                       ",
"            !!!!!!!!!!!!  !!!!!!!!!!!!!!!                       ",
"             !!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"             !!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!                         ",
"               !!!!!!!!!!!!!!!!!!!!!!!                          ",
"                !!!!!!!!!!!!!!!!!!!!!                           ",
"                 !!!!!!!!!!!!!!!!!!!                            ",
"                 !!!!!!!!!!!!!!!!!                              ",
"                  !!!!!!!!!!!!!!!!                              ",
"                  !!!!!!!!!!!!!!!!!                             ",
"                  !!!!!!!!!!!!!!!!!!                            ",
"                 !!!!!!!!!!!!!!!!!!!!!                          ",
"                 !!!!!!!!!!!!!!!!!!!!!!                         ",
"                 !!!!!!!!!!!!!!!!!!!!!!!                        ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!                       ",
"                 !!!!!!!!! !!!!!!!!!!!!!!                       ",
"                !!!!!!!!!!   !!!!!!!!!!!!!                      ",
"                !!!!!!!!!!    !!!!!!!!!!!!!                     ",
"                !!!!!!!!!!     !!!!!!!!!!!!!                    ",
"                !!!!!!!!!!      !!!!!!!!!!!!                    ",
"                !!!!!!!!!!       !!!!!!!!!!!!                   ",
"                !!!!!!!!!!        !!!!!!!!!!!                   ",
"                !!!!!!!!!!!!      !!!!!!!!!!!                   ",
"                !!!!!!!!!!!!!!!!   !!!!!!!!!!                   ",
"                !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!!!!                   ",
"                   !!!!!!!!!!!!!!!!!!!!!!!!!                    ",
"                    !!!!!!!!!!!!!!!!!!!!!!!!                    ",
"                     !!!!!!!!!!!!!!!!!!!!!!                     ",
"                        !!!!!!!!!!!!!!!!!!                      ",
"                            !!!!!!!!!!!!!                       ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempNum9[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                !!!!!!!!!!!!!!!!!!                              ",
"             !!!!!!!!!!!!!!!!!!!!!!                             ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!                            ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"       !!!!!!!!!!!!!        !!!!!!!!!                           ",
"       !!!!!!!!!!          !!!!!!!!!!                           ",
"      !!!!!!!!!!           !!!!!!!!!!                           ",
"      !!!!!!!!!!           !!!!!!!!!!                           ",
"      !!!!!!!!!!           !!!!!!!!!!                           ",
"      !!!!!!!!!!           !!!!!!!!!!                           ",
"      !!!!!!!!!            !!!!!!!!!!                           ",
"      !!!!!!!!!           !!!!!!!!!!!                           ",
"      !!!!!!!!!!        !!!!!!!!!!!!!                           ",
"      !!!!!!!!!!      !!!!!!!!!!!!!!!                           ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"         !!!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"          !!!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!                           ",
"            !!!!!!!!!!!!!!  !!!!!!!!!!                          ",
"                            !!!!!!!!!!                          ",
"                            !!!!!!!!!!                          ",
"                            !!!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!                          ",
"                             !!!!!!!!!!                         ",
"                             !!!!!!!!!!                         ",
"                             !!!!!!!!!!                         ",
"                             !!!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                              !!!!!!!!!                         ",
"                               !!!!!!!                          ",
"                                !!!!!                           ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};

/* XPM */
static xpm_row_t const tempSymbolColon[] = {
/* width height num_colors chars_per_pixel */
"64 64 2",
/* colors */
"  0",
"! 1",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                          !!!!!!!!                              ",
"                      !!!!!!!!!!!!!                             ",
"                     !!!!!!!!!!!!!!!                            ",
"                    !!!!!!!!!!!!!!!!                            ",
"                    !!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                   !!!!!!!!!!!!!!!!!                            ",
"                    !!!!!!!!!!!!!!!!                            ",
"                     !!!!!!!!!!!!!!                             ",
"                      !!!!!!!!!!!!                              ",
"                       !!!!!!!!!!                               ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                       !!!!!!!!!!                               ",
"                      !!!!!!!!!!!!                              ",
"                     !!!!!!!!!!!!!!                             ",
"                     !!!!!!!!!!!!!!!                            ",
"                    !!!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!!                           ",
"                    !!!!!!!!!!!!!!!!                            ",
"                     !!!!!!!!!!!!!!                             ",
"                      !!!!!!!!!!!!                              ",
"                        !!!!!!!!                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "
};
