#pragma once

#include <stddef.h>
#include <lcom/lcf.h>

static xpm_row_t const gajoTeste[] = {
"100 100 2",
"  0",
"! 8",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!                                                                                              !!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
};

static xpm_row_t const sun[] = {
/* width height num_colors chars_per_pixel */
"50 50 2",
"  0",
"! 6",
"                                                  ",
"                       !                          ",
"                       !                          ",
"                       !                          ",
"                       !                    !     ",
"                       !                   !!     ",
"                       !                  !!      ",
"      !!               !                 !!       ",
"       !!                               !!        ",
"        !!                             !!         ",
"         !!                            !          ",
"          !!       !!!!!!!!!!!        !!          ",
"           !!    !!!!!!!!!!!!!!!      !           ",
"                !!!!!!!!!!!!!!!!!                 ",
"               !!!!!!!!!!!!!!!!!!!                ",
"              !!!!!!!!!!!!!!!!!!!!!               ",
"             !!!!!!!!!!!!!!!!!!!!!!!              ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"   !!!!!!  !!!!!!!!!!!!!!!!!!!!!!!!!!!  !!!!!!    ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"           !!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"            !!!!!!!!!!!!!!!!!!!!!!!!!             ",
"             !!!!!!!!!!!!!!!!!!!!!!!              ",
"              !!!!!!!!!!!!!!!!!!!!!               ",
"               !!!!!!!!!!!!!!!!!!!                ",
"                !!!!!!!!!!!!!!!!!                 ",
"           !!    !!!!!!!!!!!!!!!     !            ",
"          !!       !!!!!!!!!!!       !!           ",
"         !!                           !!          ",
"        !!                             !!         ",
"       !!                !              !         ",
"      !!                 !               !        ",
"      !                  !               !!       ",
"                         !                !       ",
"                         !                        ",
"                         !                        ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "
};

static xpm_row_t const moon[] = {
/* width height num_colors chars_per_pixel */
"50 50 2",
/* colors */
"  0",
"! 7",
/* pixels */
"                                                  ",
"                                                  ",
"                        !!!!!!!!!                 ",
"                       !!!!!!!!!!!!!!             ",
"                        !!!!!!!!!!!!!!!           ",
"                           !!!!!!!!!!!!!!         ",
"                             !!!!!!!!!!!!!        ",
"                               !!!!!!!!!!!!       ",
"                                !!!!!!!!!!!       ",
"                                !!!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!      ",
"                                 !!!!!!!!!!!!     ",
"                                !!!!!!!!!!!!!     ",
"                                !!!!!!!!!!!!!     ",
"                               !!!!!!!!!!!!!!     ",
"                               !!!!!!!!!!!!!!     ",
"                              !!!!!!!!!!!!!!!     ",
"                             !!!!!!!!!!!!!!!!     ",
"                             !!!!!!!!!!!!!!!      ",
"                            !!!!!!!!!!!!!!!!      ",
"                            !!!!!!!!!!!!!!!!      ",
"                           !!!!!!!!!!!!!!!!!      ",
"                          !!!!!!!!!!!!!!!!!!      ",
"                          !!!!!!!!!!!!!!!!!!      ",
"                         !!!!!!!!!!!!!!!!!!!      ",
"                        !!!!!!!!!!!!!!!!!!!       ",
"                      !!!!!!!!!!!!!!!!!!!!!       ",
"                     !!!!!!!!!!!!!!!!!!!!!!       ",
"                  !!!!!!!!!!!!!!!!!!!!!!!!!       ",
"              !!!!!!!!!!!!!!!!!!!!!!!!!!!!        ",
"  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!         ",
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          ",
"     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
"      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            ",
"       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             ",
"        !!!!!!!!!!!!!!!!!!!!!!!!!!!               ",
"           !!!!!!!!!!!!!!!!!!!!!                  ",
"               !!!!!!!!!!!!!                      ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "
};

static xpm_row_t const train[] = {
    "100 100 4",
"  0",
"O 36",
"H 7",
"X 20",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"          HHHHHHHHHH                                                            HHHHHHHHHH          ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   ",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
